config/routes.rb
GitHubApi::Application.routes.draw do

  match '/repo'  => 'github_api#list'
  resources :github_api

  root :to => 'github_api#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/github_api_controller.rb
class GithubApiController < ApplicationController
  
  def index
  end

  def show
  end

  def list
    @user = params[:user]
    @repo = params[:repo]
    repos = Github::Client::Repos.new
    @response = repos.branches @user, @repo
    @commits = repos.commits.list @user, @repo
    @releases = repos.releases.list @user, @repo

  end

  def create
    @user = params[:user]
    password = params[:password]
    @github = Github.new basic_auth: "#{@user}:#{password}"

    begin
      @github.repos.list
    rescue
      flash[:error] = "Authentication Error!!"
      @error = true
    end
    
    render "show"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_api_helper.rb
module GithubApiHelper
end

app/views/github_api/index.html.erb
<div class="row_fluid index">
</div>

app/views/github_api/list.html.erb
<div class="row-fluid">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <h3><strong>Repositry: </strong> <%= @repo %></h3>

    <h5><strong>Commits: </strong> <%= @commits.body.size %></h5>

    <h5><strong>Releases: </strong> <%= @releases.body.size %></h5>
    <% if @response.success? %>
      <strong>Branch: </strong></br>
      <ul class="list-group">
      <% @response.body.each do |branch| %>
        <li class="list-group-item"> <%= branch.name%></li>
        <% end  %>
      </ul>
    <% else %>
      No permission to access!!!
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/github_api/show.html.erb
<div class="row-fluid">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <% unless @error %>
      <table class="table hover">
        <tr>
          <th> name</th>
          <th> created_at</th>
          <th> commits</th>
        </tr>
        <% @github.repos.list.each do |repo| %>
        <tr>
          <td><%= link_to repo.name, repo_path(:repo => repo.name, user: @user) %></td>
          <td><%= repo.created_at %></td>
          <td><%= "test" %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitHubApi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyGitHub", root_path, class: "navbar-brand" %>
      <%= link_to "Get Your Project Detail From GitHub", "#" , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag "/github_api", :method => 'post', :class=> "navbar-form navbar-right form-inline" do %>
        <div class="form-group">
          <%= label_tag :UserId %>
          <%= text_field_tag :user,"", required: true, class: "form-control" %>
         </div>
         <div class="form-group">
          <%= label_tag :password %>
          <%= password_field_tag :password,"", required: true, class: "form-control" %>
         </div>
        <%= submit_tag "Search", :name => nil , class: "btn btn-primary" %>
       <% end %>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div>
  </div>
</nav>
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<%= yield %>

</body>
</html>